### ISSUE TITLE
Implementing Block krging

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/KrigingEstimators.jl#19]
It cloud be not very complicated to have a Block kriging implementation. Block kriging is quite used in mining applications to directly estimate a larger support. Basically, it involves to compute correctly the covariance between the block and samples, using a block discretisation and to correct the block variance.

**Comment by juliohm** [comment]
This issue is already tracked in the main GeoStats.jl repo: https://github.com/JuliaEarth/GeoStats.jl/issues/40
